service: lambda-express

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  ping:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
  shortid:
    handler: index.handler
    events:
      - http:
          path: /shortid
          method: get
  uuid:
    handler: index.handler
    events:
      - http:
          path: /uuid
          method: get
  password:
    handler: index.handler
    events:
      - http:
          path: /password
          method: get