service: lambda-express-class-exercise2

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements: 
    - Effect: "Allow" 
      Action: "dynamodb:GetItem" 
      Resource:  
        - "arn:aws:dynamodb:us-east-1:988615802188:table/user"
    - Effect: "Allow" 
      Action: 
        - "s3:*" 
      Resource: 
        - "*"

functions:
  ping:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
  getFromS3:
    handler: index.handler
    events:
      - http:
          path: /get-doc/{userid}
          method: get