service: lambda-express-class-exercise3

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  ping:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
  form:
    handler: index.handler
    events:
      - http:
          path: /form
          method: get