service: my-express-application

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  myStage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  saveObjectToS3:
    handler: index.handler
    events:
      - http:
          path: savetos3
          method: post
  getObjectFromS3:
    handler: index.handler
    events:
      - http:
          path: getfroms3
          method: post
